Adds PreservationEvents to Publications.
emory-libraries/dlp-selfdeposit pull request #145
Opened 2024-03-21 13:08 UTC by bwatson78

- app/controllers/hyrax/publications_controller.rb: includes module that contains creation methods and inserts those into `create` and `update` controller actions. Also defines Publication event attribute hashes.
- app/models/preservation*: institutes model that pulls its attributes from the metadata yaml of the same name.
- app/models/publication.rb: provides Publication class with instance methods that either set or get the association between object and its preservation events.
- config/metadata/preservation*: lists the attributes with their predicates to be used in each preservation model.
- config/metadata/publication_metadata.yaml: defines an attribute that holds a comma-separated string of PreservationEvent ids.
- lib/preservation_events.rb: creates module that provides a PreservationEvent creation method.

2024-03-21 18:32 UTC, abelemlih commented
@bwatson78 since you are able to run tests locally, could you add some tests to this PR to ensure preservation event functionality is tested properly? In Curate, we currently have `spec/lib/preservation_events_spec.rb` and `spec/models/preservation_event_spec.rb`.

2024-03-21 18:33 UTC, abelemlih requested changes
@bwatson78 since you are able to run tests locally, could you add some tests to this PR to ensure preservation event functionality is tested properly? In Curate, we currently have `spec/lib/preservation_events_spec.rb` and `spec/models/preservation_event_spec.rb`.

2024-03-22 12:33 UTC, bwatson78 commented
@abelemlih Rspec added.

2024-03-25 14:54 UTC, abelemlih approved these changes

2024-03-25 14:54 UTC, merged